version: "3.7"

services:
  challenge:
    image: ghcr.io/cybermouflons/ccsc2023/asmr:latest
    restart: always
    ports:
      - 6369:6369
    build:
      context: ./setup
      dockerfile: Dockerfile
      labels:
        ctf.challenge.name: asmr
