version: "3.7"

services:
  challenge:
    image: ghcr.io/cybermouflons/ccsc2023/stack-smashing-2023:latest
    restart: always
    ports:
      - 1337:1337
    build:
      context: ./setup
      dockerfile: Dockerfile
      labels: 
        ctf.challenge.name: stack-smashing-2023