version: "3.7"

services:
  challenge:
    image: ghcr.io/cybermouflons/ccsc2023/guardians-rpc-rift:latest
    restart: always
    ports:
      - 50051:50051
      - 3000:80
    build:
      context: ./setup
      dockerfile: Dockerfile
