version: "3.7"

services:
  challenge:
    image: ghcr.io/cybermouflons/ccsc2023/Cyber_Prison_2:latest
    restart: always
    ports:
      - 4690:4690
    build:
      context: ./setup
      dockerfile: Dockerfile
      labels:
        ctf.challenge.name: Cyber_Prison_2
