version: '3'
services:

  webapp:
    build: ./setup/webapp/
    depends_on:
      - db
    ports:
      - 3000:80
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass