version: '3'
services:

  app:
    image: ghcr.io/cybermouflons/ccsc2023/cyber-sleuths-web-security-havoc:latest # Add in prod
    build: ./setup/
    ports:
      # - 3000:3000
      - 3443:3443
    environment:
      host: localhost:3443
      ccsc_host: challenges.cybermouflons.com
      admin_username: admin
      admin_password: th1s_is_4_re4lly_l0ng_password_l0o0o0oo0l_dont_guess_me_plzzz
    # volumes:              #
    #   - ./setup/views/index.html:/app/views/index.html      # Remove in prod
    #   - ./setup/views/login.html:/app/views/login.html      # Remove in prod
    #   - ./setup/views/register.html:/app/views/register.html      # Remove in prod
    #   - ./setup/static/css/styles.css:/app/static/css/styles.css      # Remove in prod
    # #   - /app/node_modules #

