version: "3.7"

services:
  challenge:
    image: ghcr.io/cybermouflons/ccsc2023/get-to-the-chopper-2:latest
    restart: always
    ports:
      - 1337:1337
    build:
      context: ./setup
      dockerfile: Dockerfile
      labels:
        ctf.challenge.name: get-to-the-chopper-2
