name: Sync CTFd

on: [workflow_call]  # allow this workflow to be called from other workflows

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create .ctf/config file
        run: |
          mkdir -p .ctf/config
          echo "${{ secrets.CTF_CLI_CONFIG }}" > .ctf/config
      
      - name: Install ctfcli
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/apogiatzis/ctfcli
      
      - name: Challenge discovery
        id: challenge-discovery
        uses: ./.github/actions/discover-challenges
        with:
          base-dir: '.'
      
      - name: Challenge Sync
        id: challenge-sync
        run: |
          IFS=' ' read -r -a chall_dirs <<< "${{ steps.challenge-discovery.outputs.dirs }}"
            for dir in "${chall_dirs[@]}"; do
                ctf challenge install ${dir}
                ctf challenge sync ${dir}
            done
          echo "dirs=${dirs[*]}" >> "$GITHUB_OUTPUT"
      