name: Challenge Pipeline


on:
  push:
    branches: ['master']

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  
  build:
    uses: ./.github/workflows/build.yml
    needs: lint

  # ctfd:
  #   uses: ./.github/workflows/ctfd.yml
  #   needs: build
  #   secrets: inherit