name: Generate README files

on: [workflow_call]  # allow this workflow to be called from other workflows

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3